//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace GiayDep.Service_Loai {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_LoaiSoap", Namespace="http://tempuri.org/")]
    public partial class Service_Loai : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LayTatCaLoaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemLoaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuaLoaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaLoaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckLoaiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_Loai() {
            this.Url = global::GiayDep.Properties.Settings.Default.GiayDep_Service_Loai_Service_Loai;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LayTatCaLoaiCompletedEventHandler LayTatCaLoaiCompleted;
        
        /// <remarks/>
        public event ThemLoaiCompletedEventHandler ThemLoaiCompleted;
        
        /// <remarks/>
        public event SuaLoaiCompletedEventHandler SuaLoaiCompleted;
        
        /// <remarks/>
        public event XoaLoaiCompletedEventHandler XoaLoaiCompleted;
        
        /// <remarks/>
        public event CheckLoaiCompletedEventHandler CheckLoaiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayTatCaLoai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Loai[] LayTatCaLoai() {
            object[] results = this.Invoke("LayTatCaLoai", new object[0]);
            return ((Loai[])(results[0]));
        }
        
        /// <remarks/>
        public void LayTatCaLoaiAsync() {
            this.LayTatCaLoaiAsync(null);
        }
        
        /// <remarks/>
        public void LayTatCaLoaiAsync(object userState) {
            if ((this.LayTatCaLoaiOperationCompleted == null)) {
                this.LayTatCaLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayTatCaLoaiOperationCompleted);
            }
            this.InvokeAsync("LayTatCaLoai", new object[0], this.LayTatCaLoaiOperationCompleted, userState);
        }
        
        private void OnLayTatCaLoaiOperationCompleted(object arg) {
            if ((this.LayTatCaLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayTatCaLoaiCompleted(this, new LayTatCaLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemLoai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemLoai(string l) {
            object[] results = this.Invoke("ThemLoai", new object[] {
                        l});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemLoaiAsync(string l) {
            this.ThemLoaiAsync(l, null);
        }
        
        /// <remarks/>
        public void ThemLoaiAsync(string l, object userState) {
            if ((this.ThemLoaiOperationCompleted == null)) {
                this.ThemLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemLoaiOperationCompleted);
            }
            this.InvokeAsync("ThemLoai", new object[] {
                        l}, this.ThemLoaiOperationCompleted, userState);
        }
        
        private void OnThemLoaiOperationCompleted(object arg) {
            if ((this.ThemLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemLoaiCompleted(this, new ThemLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuaLoai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SuaLoai(int MaLoai, string TenLoai) {
            object[] results = this.Invoke("SuaLoai", new object[] {
                        MaLoai,
                        TenLoai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SuaLoaiAsync(int MaLoai, string TenLoai) {
            this.SuaLoaiAsync(MaLoai, TenLoai, null);
        }
        
        /// <remarks/>
        public void SuaLoaiAsync(int MaLoai, string TenLoai, object userState) {
            if ((this.SuaLoaiOperationCompleted == null)) {
                this.SuaLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuaLoaiOperationCompleted);
            }
            this.InvokeAsync("SuaLoai", new object[] {
                        MaLoai,
                        TenLoai}, this.SuaLoaiOperationCompleted, userState);
        }
        
        private void OnSuaLoaiOperationCompleted(object arg) {
            if ((this.SuaLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuaLoaiCompleted(this, new SuaLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaLoai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaLoai(int MaLoai) {
            object[] results = this.Invoke("XoaLoai", new object[] {
                        MaLoai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaLoaiAsync(int MaLoai) {
            this.XoaLoaiAsync(MaLoai, null);
        }
        
        /// <remarks/>
        public void XoaLoaiAsync(int MaLoai, object userState) {
            if ((this.XoaLoaiOperationCompleted == null)) {
                this.XoaLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaLoaiOperationCompleted);
            }
            this.InvokeAsync("XoaLoai", new object[] {
                        MaLoai}, this.XoaLoaiOperationCompleted, userState);
        }
        
        private void OnXoaLoaiOperationCompleted(object arg) {
            if ((this.XoaLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaLoaiCompleted(this, new XoaLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckLoai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckLoai(string TenLoai) {
            object[] results = this.Invoke("CheckLoai", new object[] {
                        TenLoai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoaiAsync(string TenLoai) {
            this.CheckLoaiAsync(TenLoai, null);
        }
        
        /// <remarks/>
        public void CheckLoaiAsync(string TenLoai, object userState) {
            if ((this.CheckLoaiOperationCompleted == null)) {
                this.CheckLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoaiOperationCompleted);
            }
            this.InvokeAsync("CheckLoai", new object[] {
                        TenLoai}, this.CheckLoaiOperationCompleted, userState);
        }
        
        private void OnCheckLoaiOperationCompleted(object arg) {
            if ((this.CheckLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoaiCompleted(this, new CheckLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Loai {
        
        private int maLoaiField;
        
        private string tenLoaiField;
        
        private SanPham[] sanPhamsField;
        
        /// <remarks/>
        public int MaLoai {
            get {
                return this.maLoaiField;
            }
            set {
                this.maLoaiField = value;
            }
        }
        
        /// <remarks/>
        public string TenLoai {
            get {
                return this.tenLoaiField;
            }
            set {
                this.tenLoaiField = value;
            }
        }
        
        /// <remarks/>
        public SanPham[] SanPhams {
            get {
                return this.sanPhamsField;
            }
            set {
                this.sanPhamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SanPham {
        
        private int maSPField;
        
        private string tenSPField;
        
        private System.Nullable<int> maLoaiField;
        
        private string thuongHieuField;
        
        private string hinhAnhField;
        
        private string moTaField;
        
        private System.Nullable<int> maKMField;
        
        private System.Nullable<System.DateTime> ngayDangField;
        
        private string moTaCTField;
        
        private CTDH[] cTDHsField;
        
        private CTHDN[] cTHDNsField;
        
        private Kho[] khoesField;
        
        private KhuyenMai khuyenMaiField;
        
        private Loai loaiField;
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        public string TenSP {
            get {
                return this.tenSPField;
            }
            set {
                this.tenSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaLoai {
            get {
                return this.maLoaiField;
            }
            set {
                this.maLoaiField = value;
            }
        }
        
        /// <remarks/>
        public string ThuongHieu {
            get {
                return this.thuongHieuField;
            }
            set {
                this.thuongHieuField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaKM {
            get {
                return this.maKMField;
            }
            set {
                this.maKMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayDang {
            get {
                return this.ngayDangField;
            }
            set {
                this.ngayDangField = value;
            }
        }
        
        /// <remarks/>
        public string MoTaCT {
            get {
                return this.moTaCTField;
            }
            set {
                this.moTaCTField = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public Kho[] Khoes {
            get {
                return this.khoesField;
            }
            set {
                this.khoesField = value;
            }
        }
        
        /// <remarks/>
        public KhuyenMai KhuyenMai {
            get {
                return this.khuyenMaiField;
            }
            set {
                this.khuyenMaiField = value;
            }
        }
        
        /// <remarks/>
        public Loai Loai {
            get {
                return this.loaiField;
            }
            set {
                this.loaiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CTDH {
        
        private int maDHField;
        
        private int maSPField;
        
        private int maSizeField;
        
        private int maMauField;
        
        private System.Nullable<int> slField;
        
        private System.Nullable<decimal> donGiaField;
        
        private DonHang donHangField;
        
        private Mau mauField;
        
        private SanPham sanPhamField;
        
        private Size sizeField;
        
        /// <remarks/>
        public int MaDH {
            get {
                return this.maDHField;
            }
            set {
                this.maDHField = value;
            }
        }
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        public int MaSize {
            get {
                return this.maSizeField;
            }
            set {
                this.maSizeField = value;
            }
        }
        
        /// <remarks/>
        public int MaMau {
            get {
                return this.maMauField;
            }
            set {
                this.maMauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DonGia {
            get {
                return this.donGiaField;
            }
            set {
                this.donGiaField = value;
            }
        }
        
        /// <remarks/>
        public DonHang DonHang {
            get {
                return this.donHangField;
            }
            set {
                this.donHangField = value;
            }
        }
        
        /// <remarks/>
        public Mau Mau {
            get {
                return this.mauField;
            }
            set {
                this.mauField = value;
            }
        }
        
        /// <remarks/>
        public SanPham SanPham {
            get {
                return this.sanPhamField;
            }
            set {
                this.sanPhamField = value;
            }
        }
        
        /// <remarks/>
        public Size Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DonHang {
        
        private int maDHField;
        
        private System.Nullable<int> maKHField;
        
        private System.Nullable<System.DateTime> ngayMuaField;
        
        private System.Nullable<decimal> tongTienField;
        
        private System.Nullable<int> tinhTrangField;
        
        private string nVDuyetField;
        
        private CTDH[] cTDHsField;
        
        private KhachHang khachHangField;
        
        /// <remarks/>
        public int MaDH {
            get {
                return this.maDHField;
            }
            set {
                this.maDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaKH {
            get {
                return this.maKHField;
            }
            set {
                this.maKHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayMua {
            get {
                return this.ngayMuaField;
            }
            set {
                this.ngayMuaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.tongTienField;
            }
            set {
                this.tongTienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                this.tinhTrangField = value;
            }
        }
        
        /// <remarks/>
        public string NVDuyet {
            get {
                return this.nVDuyetField;
            }
            set {
                this.nVDuyetField = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public KhachHang KhachHang {
            get {
                return this.khachHangField;
            }
            set {
                this.khachHangField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KhachHang {
        
        private int maKHField;
        
        private string hoTenField;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string emailField;
        
        private string matKhauField;
        
        private string sDTField;
        
        private string diaChiField;
        
        private string gioiTinhField;
        
        private System.Nullable<System.DateTime> ngayDangKiField;
        
        private DonHang[] donHangsField;
        
        /// <remarks/>
        public int MaKH {
            get {
                return this.maKHField;
            }
            set {
                this.maKHField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayDangKi {
            get {
                return this.ngayDangKiField;
            }
            set {
                this.ngayDangKiField = value;
            }
        }
        
        /// <remarks/>
        public DonHang[] DonHangs {
            get {
                return this.donHangsField;
            }
            set {
                this.donHangsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KhuyenMai {
        
        private int maKMField;
        
        private string tenKMField;
        
        private System.Nullable<System.DateTime> ngayBDField;
        
        private System.Nullable<System.DateTime> ngayKTField;
        
        private SanPham[] sanPhamsField;
        
        /// <remarks/>
        public int MaKM {
            get {
                return this.maKMField;
            }
            set {
                this.maKMField = value;
            }
        }
        
        /// <remarks/>
        public string TenKM {
            get {
                return this.tenKMField;
            }
            set {
                this.tenKMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayBD {
            get {
                return this.ngayBDField;
            }
            set {
                this.ngayBDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayKT {
            get {
                return this.ngayKTField;
            }
            set {
                this.ngayKTField = value;
            }
        }
        
        /// <remarks/>
        public SanPham[] SanPhams {
            get {
                return this.sanPhamsField;
            }
            set {
                this.sanPhamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kho {
        
        private int maSPField;
        
        private int maMauField;
        
        private int maSizeField;
        
        private System.Nullable<int> slField;
        
        private System.Nullable<decimal> giaBanField;
        
        private System.Nullable<decimal> giaNhapField;
        
        private Mau mauField;
        
        private SanPham sanPhamField;
        
        private Size sizeField;
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        public int MaMau {
            get {
                return this.maMauField;
            }
            set {
                this.maMauField = value;
            }
        }
        
        /// <remarks/>
        public int MaSize {
            get {
                return this.maSizeField;
            }
            set {
                this.maSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GiaBan {
            get {
                return this.giaBanField;
            }
            set {
                this.giaBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.giaNhapField;
            }
            set {
                this.giaNhapField = value;
            }
        }
        
        /// <remarks/>
        public Mau Mau {
            get {
                return this.mauField;
            }
            set {
                this.mauField = value;
            }
        }
        
        /// <remarks/>
        public SanPham SanPham {
            get {
                return this.sanPhamField;
            }
            set {
                this.sanPhamField = value;
            }
        }
        
        /// <remarks/>
        public Size Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mau {
        
        private int maMauField;
        
        private string tenMauField;
        
        private CTDH[] cTDHsField;
        
        private CTHDN[] cTHDNsField;
        
        private Kho[] khoesField;
        
        /// <remarks/>
        public int MaMau {
            get {
                return this.maMauField;
            }
            set {
                this.maMauField = value;
            }
        }
        
        /// <remarks/>
        public string TenMau {
            get {
                return this.tenMauField;
            }
            set {
                this.tenMauField = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public Kho[] Khoes {
            get {
                return this.khoesField;
            }
            set {
                this.khoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CTHDN {
        
        private int maHDNField;
        
        private int maSPField;
        
        private int maMauField;
        
        private int maSizeField;
        
        private System.Nullable<int> slField;
        
        private System.Nullable<decimal> giaNhapField;
        
        private HDNhap hDNhapField;
        
        private Mau mauField;
        
        private SanPham sanPhamField;
        
        private Size sizeField;
        
        /// <remarks/>
        public int MaHDN {
            get {
                return this.maHDNField;
            }
            set {
                this.maHDNField = value;
            }
        }
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        public int MaMau {
            get {
                return this.maMauField;
            }
            set {
                this.maMauField = value;
            }
        }
        
        /// <remarks/>
        public int MaSize {
            get {
                return this.maSizeField;
            }
            set {
                this.maSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.giaNhapField;
            }
            set {
                this.giaNhapField = value;
            }
        }
        
        /// <remarks/>
        public HDNhap HDNhap {
            get {
                return this.hDNhapField;
            }
            set {
                this.hDNhapField = value;
            }
        }
        
        /// <remarks/>
        public Mau Mau {
            get {
                return this.mauField;
            }
            set {
                this.mauField = value;
            }
        }
        
        /// <remarks/>
        public SanPham SanPham {
            get {
                return this.sanPhamField;
            }
            set {
                this.sanPhamField = value;
            }
        }
        
        /// <remarks/>
        public Size Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HDNhap {
        
        private int maHDNField;
        
        private System.Nullable<int> maNCCField;
        
        private System.Nullable<int> maNVField;
        
        private System.Nullable<System.DateTime> ngayNhapField;
        
        private System.Nullable<decimal> tongTienField;
        
        private System.Nullable<int> tinhTrangField;
        
        private CTHDN[] cTHDNsField;
        
        private NhaCungCap nhaCungCapField;
        
        private NhanVien nhanVienField;
        
        /// <remarks/>
        public int MaHDN {
            get {
                return this.maHDNField;
            }
            set {
                this.maHDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaNCC {
            get {
                return this.maNCCField;
            }
            set {
                this.maNCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaNV {
            get {
                return this.maNVField;
            }
            set {
                this.maNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.ngayNhapField;
            }
            set {
                this.ngayNhapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.tongTienField;
            }
            set {
                this.tongTienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                this.tinhTrangField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public NhaCungCap NhaCungCap {
            get {
                return this.nhaCungCapField;
            }
            set {
                this.nhaCungCapField = value;
            }
        }
        
        /// <remarks/>
        public NhanVien NhanVien {
            get {
                return this.nhanVienField;
            }
            set {
                this.nhanVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NhaCungCap {
        
        private int maNCCField;
        
        private string tenNCCField;
        
        private string diaChiField;
        
        private string sDTField;
        
        private string soTKField;
        
        private HDNhap[] hDNhapsField;
        
        /// <remarks/>
        public int MaNCC {
            get {
                return this.maNCCField;
            }
            set {
                this.maNCCField = value;
            }
        }
        
        /// <remarks/>
        public string TenNCC {
            get {
                return this.tenNCCField;
            }
            set {
                this.tenNCCField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string SoTK {
            get {
                return this.soTKField;
            }
            set {
                this.soTKField = value;
            }
        }
        
        /// <remarks/>
        public HDNhap[] HDNhaps {
            get {
                return this.hDNhapsField;
            }
            set {
                this.hDNhapsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NhanVien {
        
        private int maNVField;
        
        private string hoTenField;
        
        private string emailField;
        
        private string matKhauField;
        
        private string diaChiField;
        
        private string sDTField;
        
        private string cMNDField;
        
        private System.Nullable<int> quyenAdminField;
        
        private HDNhap[] hDNhapsField;
        
        /// <remarks/>
        public int MaNV {
            get {
                return this.maNVField;
            }
            set {
                this.maNVField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string SDT {
            get {
                return this.sDTField;
            }
            set {
                this.sDTField = value;
            }
        }
        
        /// <remarks/>
        public string CMND {
            get {
                return this.cMNDField;
            }
            set {
                this.cMNDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuyenAdmin {
            get {
                return this.quyenAdminField;
            }
            set {
                this.quyenAdminField = value;
            }
        }
        
        /// <remarks/>
        public HDNhap[] HDNhaps {
            get {
                return this.hDNhapsField;
            }
            set {
                this.hDNhapsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Size {
        
        private int maSizeField;
        
        private System.Nullable<int> size1Field;
        
        private CTDH[] cTDHsField;
        
        private CTHDN[] cTHDNsField;
        
        private Kho[] khoesField;
        
        /// <remarks/>
        public int MaSize {
            get {
                return this.maSizeField;
            }
            set {
                this.maSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Size1 {
            get {
                return this.size1Field;
            }
            set {
                this.size1Field = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public Kho[] Khoes {
            get {
                return this.khoesField;
            }
            set {
                this.khoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LayTatCaLoaiCompletedEventHandler(object sender, LayTatCaLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayTatCaLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayTatCaLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Loai[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Loai[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ThemLoaiCompletedEventHandler(object sender, ThemLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SuaLoaiCompletedEventHandler(object sender, SuaLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuaLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuaLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void XoaLoaiCompletedEventHandler(object sender, XoaLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CheckLoaiCompletedEventHandler(object sender, CheckLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591