//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GiayDep.Service_KhachHang {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_KhachHangSoap", Namespace="http://tempuri.org/")]
    public partial class Service_KhachHang : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LayTatCaKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiemKhachHang_GioiTinhOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiemKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_KhachHang() {
            this.Url = global::GiayDep.Properties.Settings.Default.GiayDep_Service_KhachHang_Service_KhachHang;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LayTatCaKhachHangCompletedEventHandler LayTatCaKhachHangCompleted;
        
        /// <remarks/>
        public event XoaKhachHangCompletedEventHandler XoaKhachHangCompleted;
        
        /// <remarks/>
        public event TimKiemKhachHang_GioiTinhCompletedEventHandler TimKiemKhachHang_GioiTinhCompleted;
        
        /// <remarks/>
        public event TimKiemKhachHangCompletedEventHandler TimKiemKhachHangCompleted;
        
        /// <remarks/>
        public event ThemKhachHangCompletedEventHandler ThemKhachHangCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayTatCaKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KhachHang[] LayTatCaKhachHang() {
            object[] results = this.Invoke("LayTatCaKhachHang", new object[0]);
            return ((KhachHang[])(results[0]));
        }
        
        /// <remarks/>
        public void LayTatCaKhachHangAsync() {
            this.LayTatCaKhachHangAsync(null);
        }
        
        /// <remarks/>
        public void LayTatCaKhachHangAsync(object userState) {
            if ((this.LayTatCaKhachHangOperationCompleted == null)) {
                this.LayTatCaKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayTatCaKhachHangOperationCompleted);
            }
            this.InvokeAsync("LayTatCaKhachHang", new object[0], this.LayTatCaKhachHangOperationCompleted, userState);
        }
        
        private void OnLayTatCaKhachHangOperationCompleted(object arg) {
            if ((this.LayTatCaKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayTatCaKhachHangCompleted(this, new LayTatCaKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaKhachHang(int MaKH) {
            object[] results = this.Invoke("XoaKhachHang", new object[] {
                        MaKH});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaKhachHangAsync(int MaKH) {
            this.XoaKhachHangAsync(MaKH, null);
        }
        
        /// <remarks/>
        public void XoaKhachHangAsync(int MaKH, object userState) {
            if ((this.XoaKhachHangOperationCompleted == null)) {
                this.XoaKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaKhachHangOperationCompleted);
            }
            this.InvokeAsync("XoaKhachHang", new object[] {
                        MaKH}, this.XoaKhachHangOperationCompleted, userState);
        }
        
        private void OnXoaKhachHangOperationCompleted(object arg) {
            if ((this.XoaKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaKhachHangCompleted(this, new XoaKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiemKhachHang_GioiTinh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KhachHang[] TimKiemKhachHang_GioiTinh(string HoTen, string SoDT, string Email, int GioiTinh) {
            object[] results = this.Invoke("TimKiemKhachHang_GioiTinh", new object[] {
                        HoTen,
                        SoDT,
                        Email,
                        GioiTinh});
            return ((KhachHang[])(results[0]));
        }
        
        /// <remarks/>
        public void TimKiemKhachHang_GioiTinhAsync(string HoTen, string SoDT, string Email, int GioiTinh) {
            this.TimKiemKhachHang_GioiTinhAsync(HoTen, SoDT, Email, GioiTinh, null);
        }
        
        /// <remarks/>
        public void TimKiemKhachHang_GioiTinhAsync(string HoTen, string SoDT, string Email, int GioiTinh, object userState) {
            if ((this.TimKiemKhachHang_GioiTinhOperationCompleted == null)) {
                this.TimKiemKhachHang_GioiTinhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiemKhachHang_GioiTinhOperationCompleted);
            }
            this.InvokeAsync("TimKiemKhachHang_GioiTinh", new object[] {
                        HoTen,
                        SoDT,
                        Email,
                        GioiTinh}, this.TimKiemKhachHang_GioiTinhOperationCompleted, userState);
        }
        
        private void OnTimKiemKhachHang_GioiTinhOperationCompleted(object arg) {
            if ((this.TimKiemKhachHang_GioiTinhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiemKhachHang_GioiTinhCompleted(this, new TimKiemKhachHang_GioiTinhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiemKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KhachHang[] TimKiemKhachHang(string HoTen, string SoDT, string Email) {
            object[] results = this.Invoke("TimKiemKhachHang", new object[] {
                        HoTen,
                        SoDT,
                        Email});
            return ((KhachHang[])(results[0]));
        }
        
        /// <remarks/>
        public void TimKiemKhachHangAsync(string HoTen, string SoDT, string Email) {
            this.TimKiemKhachHangAsync(HoTen, SoDT, Email, null);
        }
        
        /// <remarks/>
        public void TimKiemKhachHangAsync(string HoTen, string SoDT, string Email, object userState) {
            if ((this.TimKiemKhachHangOperationCompleted == null)) {
                this.TimKiemKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiemKhachHangOperationCompleted);
            }
            this.InvokeAsync("TimKiemKhachHang", new object[] {
                        HoTen,
                        SoDT,
                        Email}, this.TimKiemKhachHangOperationCompleted, userState);
        }
        
        private void OnTimKiemKhachHangOperationCompleted(object arg) {
            if ((this.TimKiemKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiemKhachHangCompleted(this, new TimKiemKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemKhachHang(string HoTen, string SDT, string Email, string MatKhau, string NgaySinh, string DiaChi, int GioiTinh) {
            object[] results = this.Invoke("ThemKhachHang", new object[] {
                        HoTen,
                        SDT,
                        Email,
                        MatKhau,
                        NgaySinh,
                        DiaChi,
                        GioiTinh});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemKhachHangAsync(string HoTen, string SDT, string Email, string MatKhau, string NgaySinh, string DiaChi, int GioiTinh) {
            this.ThemKhachHangAsync(HoTen, SDT, Email, MatKhau, NgaySinh, DiaChi, GioiTinh, null);
        }
        
        /// <remarks/>
        public void ThemKhachHangAsync(string HoTen, string SDT, string Email, string MatKhau, string NgaySinh, string DiaChi, int GioiTinh, object userState) {
            if ((this.ThemKhachHangOperationCompleted == null)) {
                this.ThemKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemKhachHangOperationCompleted);
            }
            this.InvokeAsync("ThemKhachHang", new object[] {
                        HoTen,
                        SDT,
                        Email,
                        MatKhau,
                        NgaySinh,
                        DiaChi,
                        GioiTinh}, this.ThemKhachHangOperationCompleted, userState);
        }
        
        private void OnThemKhachHangOperationCompleted(object arg) {
            if ((this.ThemKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemKhachHangCompleted(this, new ThemKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KhachHang Login(string email, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        email,
                        password});
            return ((KhachHang)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        email,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KhachHang {
        
        private int maKHField;
        
        private string hoTenField;
        
        private string soDTField;
        
        private string emailField;
        
        private string matKhauField;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string diaChiField;
        
        private System.Nullable<int> gioiTinhField;
        
        private DonHang[] donHangsField;
        
        /// <remarks/>
        public int MaKH {
            get {
                return this.maKHField;
            }
            set {
                this.maKHField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string SoDT {
            get {
                return this.soDTField;
            }
            set {
                this.soDTField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        public DonHang[] DonHangs {
            get {
                return this.donHangsField;
            }
            set {
                this.donHangsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DonHang {
        
        private int maDHField;
        
        private int maKHField;
        
        private System.Nullable<System.DateTime> ngayLapField;
        
        private System.Nullable<decimal> tongTienField;
        
        private CTDH[] cTDHsField;
        
        private KhachHang khachHangField;
        
        private TinhTrang[] tinhTrangsField;
        
        /// <remarks/>
        public int MaDH {
            get {
                return this.maDHField;
            }
            set {
                this.maDHField = value;
            }
        }
        
        /// <remarks/>
        public int MaKH {
            get {
                return this.maKHField;
            }
            set {
                this.maKHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayLap {
            get {
                return this.ngayLapField;
            }
            set {
                this.ngayLapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.tongTienField;
            }
            set {
                this.tongTienField = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public KhachHang KhachHang {
            get {
                return this.khachHangField;
            }
            set {
                this.khachHangField = value;
            }
        }
        
        /// <remarks/>
        public TinhTrang[] TinhTrangs {
            get {
                return this.tinhTrangsField;
            }
            set {
                this.tinhTrangsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CTDH {
        
        private int maDHField;
        
        private int maSPField;
        
        private System.Nullable<int> soLuongField;
        
        private System.Nullable<decimal> donGiaField;
        
        private System.Nullable<int> sizeField;
        
        private string mauField;
        
        private DonHang donHangField;
        
        private SanPham sanPhamField;
        
        /// <remarks/>
        public int MaDH {
            get {
                return this.maDHField;
            }
            set {
                this.maDHField = value;
            }
        }
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SoLuong {
            get {
                return this.soLuongField;
            }
            set {
                this.soLuongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DonGia {
            get {
                return this.donGiaField;
            }
            set {
                this.donGiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public string Mau {
            get {
                return this.mauField;
            }
            set {
                this.mauField = value;
            }
        }
        
        /// <remarks/>
        public DonHang DonHang {
            get {
                return this.donHangField;
            }
            set {
                this.donHangField = value;
            }
        }
        
        /// <remarks/>
        public SanPham SanPham {
            get {
                return this.sanPhamField;
            }
            set {
                this.sanPhamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SanPham {
        
        private int maSPField;
        
        private string tenSPField;
        
        private System.Nullable<int> maLoaiField;
        
        private string thuongHieuField;
        
        private System.Nullable<decimal> giaSPField;
        
        private string hinhAnhField;
        
        private string hinhAnh1Field;
        
        private string hinhAnh2Field;
        
        private string hinhAnh3Field;
        
        private System.Nullable<int> soLuongField;
        
        private string moTaField;
        
        private System.Nullable<int> kmField;
        
        private System.Nullable<System.DateTime> ngayCapNhatField;
        
        private System.Nullable<int> giaKMField;
        
        private string mauField;
        
        private CTDH[] cTDHsField;
        
        private CTHDN[] cTHDNsField;
        
        private Loai loaiField;
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        public string TenSP {
            get {
                return this.tenSPField;
            }
            set {
                this.tenSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaLoai {
            get {
                return this.maLoaiField;
            }
            set {
                this.maLoaiField = value;
            }
        }
        
        /// <remarks/>
        public string ThuongHieu {
            get {
                return this.thuongHieuField;
            }
            set {
                this.thuongHieuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GiaSP {
            get {
                return this.giaSPField;
            }
            set {
                this.giaSPField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh {
            get {
                return this.hinhAnhField;
            }
            set {
                this.hinhAnhField = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh1 {
            get {
                return this.hinhAnh1Field;
            }
            set {
                this.hinhAnh1Field = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh2 {
            get {
                return this.hinhAnh2Field;
            }
            set {
                this.hinhAnh2Field = value;
            }
        }
        
        /// <remarks/>
        public string HinhAnh3 {
            get {
                return this.hinhAnh3Field;
            }
            set {
                this.hinhAnh3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SoLuong {
            get {
                return this.soLuongField;
            }
            set {
                this.soLuongField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> KM {
            get {
                return this.kmField;
            }
            set {
                this.kmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GiaKM {
            get {
                return this.giaKMField;
            }
            set {
                this.giaKMField = value;
            }
        }
        
        /// <remarks/>
        public string Mau {
            get {
                return this.mauField;
            }
            set {
                this.mauField = value;
            }
        }
        
        /// <remarks/>
        public CTDH[] CTDHs {
            get {
                return this.cTDHsField;
            }
            set {
                this.cTDHsField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public Loai Loai {
            get {
                return this.loaiField;
            }
            set {
                this.loaiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CTHDN {
        
        private int maHDNField;
        
        private int maSPField;
        
        private System.Nullable<int> soLuongField;
        
        private System.Nullable<decimal> donGiaField;
        
        private HoaDonNhap hoaDonNhapField;
        
        private SanPham sanPhamField;
        
        /// <remarks/>
        public int MaHDN {
            get {
                return this.maHDNField;
            }
            set {
                this.maHDNField = value;
            }
        }
        
        /// <remarks/>
        public int MaSP {
            get {
                return this.maSPField;
            }
            set {
                this.maSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SoLuong {
            get {
                return this.soLuongField;
            }
            set {
                this.soLuongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DonGia {
            get {
                return this.donGiaField;
            }
            set {
                this.donGiaField = value;
            }
        }
        
        /// <remarks/>
        public HoaDonNhap HoaDonNhap {
            get {
                return this.hoaDonNhapField;
            }
            set {
                this.hoaDonNhapField = value;
            }
        }
        
        /// <remarks/>
        public SanPham SanPham {
            get {
                return this.sanPhamField;
            }
            set {
                this.sanPhamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HoaDonNhap {
        
        private int maHDNField;
        
        private int maNCCField;
        
        private System.Nullable<int> maNVField;
        
        private System.Nullable<System.DateTime> ngayLapField;
        
        private System.Nullable<decimal> tongTienField;
        
        private System.Nullable<int> tinhTrangField;
        
        private CTHDN[] cTHDNsField;
        
        private NhaCungCap nhaCungCapField;
        
        private NhanVien nhanVienField;
        
        /// <remarks/>
        public int MaHDN {
            get {
                return this.maHDNField;
            }
            set {
                this.maHDNField = value;
            }
        }
        
        /// <remarks/>
        public int MaNCC {
            get {
                return this.maNCCField;
            }
            set {
                this.maNCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaNV {
            get {
                return this.maNVField;
            }
            set {
                this.maNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgayLap {
            get {
                return this.ngayLapField;
            }
            set {
                this.ngayLapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.tongTienField;
            }
            set {
                this.tongTienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TinhTrang {
            get {
                return this.tinhTrangField;
            }
            set {
                this.tinhTrangField = value;
            }
        }
        
        /// <remarks/>
        public CTHDN[] CTHDNs {
            get {
                return this.cTHDNsField;
            }
            set {
                this.cTHDNsField = value;
            }
        }
        
        /// <remarks/>
        public NhaCungCap NhaCungCap {
            get {
                return this.nhaCungCapField;
            }
            set {
                this.nhaCungCapField = value;
            }
        }
        
        /// <remarks/>
        public NhanVien NhanVien {
            get {
                return this.nhanVienField;
            }
            set {
                this.nhanVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NhaCungCap {
        
        private int maNCCField;
        
        private string tenNCCField;
        
        private string diaChiField;
        
        private string soDTField;
        
        private string soTKField;
        
        private HoaDonNhap[] hoaDonNhapsField;
        
        /// <remarks/>
        public int MaNCC {
            get {
                return this.maNCCField;
            }
            set {
                this.maNCCField = value;
            }
        }
        
        /// <remarks/>
        public string TenNCC {
            get {
                return this.tenNCCField;
            }
            set {
                this.tenNCCField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string SoDT {
            get {
                return this.soDTField;
            }
            set {
                this.soDTField = value;
            }
        }
        
        /// <remarks/>
        public string SoTK {
            get {
                return this.soTKField;
            }
            set {
                this.soTKField = value;
            }
        }
        
        /// <remarks/>
        public HoaDonNhap[] HoaDonNhaps {
            get {
                return this.hoaDonNhapsField;
            }
            set {
                this.hoaDonNhapsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Loai {
        
        private int maLoaiField;
        
        private string tenLoaiField;
        
        private SanPham[] sanPhamsField;
        
        /// <remarks/>
        public int MaLoai {
            get {
                return this.maLoaiField;
            }
            set {
                this.maLoaiField = value;
            }
        }
        
        /// <remarks/>
        public string TenLoai {
            get {
                return this.tenLoaiField;
            }
            set {
                this.tenLoaiField = value;
            }
        }
        
        /// <remarks/>
        public SanPham[] SanPhams {
            get {
                return this.sanPhamsField;
            }
            set {
                this.sanPhamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TinhTrang {
        
        private int maDHField;
        
        private int maNVField;
        
        private System.Nullable<int> tinhTrang1Field;
        
        private DonHang donHangField;
        
        private NhanVien nhanVienField;
        
        /// <remarks/>
        public int MaDH {
            get {
                return this.maDHField;
            }
            set {
                this.maDHField = value;
            }
        }
        
        /// <remarks/>
        public int MaNV {
            get {
                return this.maNVField;
            }
            set {
                this.maNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TinhTrang1 {
            get {
                return this.tinhTrang1Field;
            }
            set {
                this.tinhTrang1Field = value;
            }
        }
        
        /// <remarks/>
        public DonHang DonHang {
            get {
                return this.donHangField;
            }
            set {
                this.donHangField = value;
            }
        }
        
        /// <remarks/>
        public NhanVien NhanVien {
            get {
                return this.nhanVienField;
            }
            set {
                this.nhanVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NhanVien {
        
        private int maNVField;
        
        private string hoTenField;
        
        private string emailField;
        
        private string soDTField;
        
        private string cMNDField;
        
        private string diaChiField;
        
        private string matKhauField;
        
        private System.Nullable<int> quyenAdminField;
        
        private HoaDonNhap[] hoaDonNhapsField;
        
        private TinhTrang[] tinhTrangsField;
        
        /// <remarks/>
        public int MaNV {
            get {
                return this.maNVField;
            }
            set {
                this.maNVField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string SoDT {
            get {
                return this.soDTField;
            }
            set {
                this.soDTField = value;
            }
        }
        
        /// <remarks/>
        public string CMND {
            get {
                return this.cMNDField;
            }
            set {
                this.cMNDField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuyenAdmin {
            get {
                return this.quyenAdminField;
            }
            set {
                this.quyenAdminField = value;
            }
        }
        
        /// <remarks/>
        public HoaDonNhap[] HoaDonNhaps {
            get {
                return this.hoaDonNhapsField;
            }
            set {
                this.hoaDonNhapsField = value;
            }
        }
        
        /// <remarks/>
        public TinhTrang[] TinhTrangs {
            get {
                return this.tinhTrangsField;
            }
            set {
                this.tinhTrangsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LayTatCaKhachHangCompletedEventHandler(object sender, LayTatCaKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayTatCaKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayTatCaKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KhachHang[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KhachHang[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void XoaKhachHangCompletedEventHandler(object sender, XoaKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void TimKiemKhachHang_GioiTinhCompletedEventHandler(object sender, TimKiemKhachHang_GioiTinhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiemKhachHang_GioiTinhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiemKhachHang_GioiTinhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KhachHang[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KhachHang[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void TimKiemKhachHangCompletedEventHandler(object sender, TimKiemKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiemKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiemKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KhachHang[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KhachHang[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ThemKhachHangCompletedEventHandler(object sender, ThemKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KhachHang Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KhachHang)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591