//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiayDep.Service_CTDH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham_Price", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SanPham_Price : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GiaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayDangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal _GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal _GiaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _NgayDangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _TenMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GiaSP {
            get {
                return this.GiaSPField;
            }
            set {
                if ((this.GiaSPField.Equals(value) != true)) {
                    this.GiaSPField = value;
                    this.RaisePropertyChanged("GiaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayDang {
            get {
                return this.NgayDangField;
            }
            set {
                if ((this.NgayDangField.Equals(value) != true)) {
                    this.NgayDangField = value;
                    this.RaisePropertyChanged("NgayDang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenMau {
            get {
                return this.TenMauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMauField, value) != true)) {
                    this.TenMauField = value;
                    this.RaisePropertyChanged("TenMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal _GiaBan {
            get {
                return this._GiaBanField;
            }
            set {
                if ((this._GiaBanField.Equals(value) != true)) {
                    this._GiaBanField = value;
                    this.RaisePropertyChanged("_GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal _GiaSP {
            get {
                return this._GiaSPField;
            }
            set {
                if ((this._GiaSPField.Equals(value) != true)) {
                    this._GiaSPField = value;
                    this.RaisePropertyChanged("_GiaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _HinhAnh {
            get {
                return this._HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this._HinhAnhField, value) != true)) {
                    this._HinhAnhField = value;
                    this.RaisePropertyChanged("_HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _MaMau {
            get {
                return this._MaMauField;
            }
            set {
                if ((this._MaMauField.Equals(value) != true)) {
                    this._MaMauField = value;
                    this.RaisePropertyChanged("_MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _MaSP {
            get {
                return this._MaSPField;
            }
            set {
                if ((this._MaSPField.Equals(value) != true)) {
                    this._MaSPField = value;
                    this.RaisePropertyChanged("_MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _NgayDang {
            get {
                return this._NgayDangField;
            }
            set {
                if ((this._NgayDangField.Equals(value) != true)) {
                    this._NgayDangField = value;
                    this.RaisePropertyChanged("_NgayDang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _Size {
            get {
                return this._SizeField;
            }
            set {
                if ((this._SizeField.Equals(value) != true)) {
                    this._SizeField = value;
                    this.RaisePropertyChanged("_Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _TenMau {
            get {
                return this._TenMauField;
            }
            set {
                if ((object.ReferenceEquals(this._TenMauField, value) != true)) {
                    this._TenMauField = value;
                    this.RaisePropertyChanged("_TenMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _TenSP {
            get {
                return this._TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this._TenSPField, value) != true)) {
                    this._TenSPField = value;
                    this.RaisePropertyChanged("_TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTDH", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CTDH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.DonHang DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.DonHang DonHang {
            get {
                return this.DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangField, value) != true)) {
                    this.DonHangField = value;
                    this.RaisePropertyChanged("DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.KhachHang KhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NVDuyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayMuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.KhachHang KhachHang {
            get {
                return this.KhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachHangField, value) != true)) {
                    this.KhachHangField = value;
                    this.RaisePropertyChanged("KhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NVDuyet {
            get {
                return this.NVDuyetField;
            }
            set {
                if ((object.ReferenceEquals(this.NVDuyetField, value) != true)) {
                    this.NVDuyetField = value;
                    this.RaisePropertyChanged("NVDuyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayMua {
            get {
                return this.NgayMuaField;
            }
            set {
                if ((this.NgayMuaField.Equals(value) != true)) {
                    this.NgayMuaField = value;
                    this.RaisePropertyChanged("NgayMua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mau", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Mau : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Kho[] KhoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMauField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenMau {
            get {
                return this.TenMauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMauField, value) != true)) {
                    this.TenMauField = value;
                    this.RaisePropertyChanged("TenMau");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Kho[] KhoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.KhuyenMai KhuyenMaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Loai LoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayDangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThuongHieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.KhuyenMai KhuyenMai {
            get {
                return this.KhuyenMaiField;
            }
            set {
                if ((object.ReferenceEquals(this.KhuyenMaiField, value) != true)) {
                    this.KhuyenMaiField = value;
                    this.RaisePropertyChanged("KhuyenMai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Loai Loai {
            get {
                return this.LoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiField, value) != true)) {
                    this.LoaiField = value;
                    this.RaisePropertyChanged("Loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaKM {
            get {
                return this.MaKMField;
            }
            set {
                if ((this.MaKMField.Equals(value) != true)) {
                    this.MaKMField = value;
                    this.RaisePropertyChanged("MaKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTaCT {
            get {
                return this.MoTaCTField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaCTField, value) != true)) {
                    this.MoTaCTField = value;
                    this.RaisePropertyChanged("MoTaCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayDang {
            get {
                return this.NgayDangField;
            }
            set {
                if ((this.NgayDangField.Equals(value) != true)) {
                    this.NgayDangField = value;
                    this.RaisePropertyChanged("NgayDang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThuongHieu {
            get {
                return this.ThuongHieuField;
            }
            set {
                if ((object.ReferenceEquals(this.ThuongHieuField, value) != true)) {
                    this.ThuongHieuField = value;
                    this.RaisePropertyChanged("ThuongHieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Size", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Size : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Kho[] KhoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Size1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size1 {
            get {
                return this.Size1Field;
            }
            set {
                if ((this.Size1Field.Equals(value) != true)) {
                    this.Size1Field = value;
                    this.RaisePropertyChanged("Size1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.DonHang[] DonHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayDangKiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayDangKi {
            get {
                return this.NgayDangKiField;
            }
            set {
                if ((this.NgayDangKiField.Equals(value) != true)) {
                    this.NgayDangKiField = value;
                    this.RaisePropertyChanged("NgayDangKi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHDN", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CTHDN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.HDNhap HDNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaHDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.GiaNhapField;
            }
            set {
                if ((this.GiaNhapField.Equals(value) != true)) {
                    this.GiaNhapField = value;
                    this.RaisePropertyChanged("GiaNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.HDNhap HDNhap {
            get {
                return this.HDNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapField, value) != true)) {
                    this.HDNhapField = value;
                    this.RaisePropertyChanged("HDNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaHDN {
            get {
                return this.MaHDNField;
            }
            set {
                if ((this.MaHDNField.Equals(value) != true)) {
                    this.MaHDNField = value;
                    this.RaisePropertyChanged("MaHDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kho", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Kho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.GiaNhapField;
            }
            set {
                if ((this.GiaNhapField.Equals(value) != true)) {
                    this.GiaNhapField = value;
                    this.RaisePropertyChanged("GiaNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HDNhap", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class HDNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaHDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.NhaCungCap NhaCungCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.NhanVien NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaHDN {
            get {
                return this.MaHDNField;
            }
            set {
                if ((this.MaHDNField.Equals(value) != true)) {
                    this.MaHDNField = value;
                    this.RaisePropertyChanged("MaHDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.NhaCungCap NhaCungCap {
            get {
                return this.NhaCungCapField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaCungCapField, value) != true)) {
                    this.NhaCungCapField = value;
                    this.RaisePropertyChanged("NhaCungCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaCungCap", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class NhaCungCap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.HDNhap[] HDNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNCCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.HDNhap[] HDNhaps {
            get {
                return this.HDNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapsField, value) != true)) {
                    this.HDNhapsField = value;
                    this.RaisePropertyChanged("HDNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTK {
            get {
                return this.SoTKField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTKField, value) != true)) {
                    this.SoTKField = value;
                    this.RaisePropertyChanged("SoTK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNCC {
            get {
                return this.TenNCCField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNCCField, value) != true)) {
                    this.TenNCCField = value;
                    this.RaisePropertyChanged("TenNCC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class NhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.HDNhap[] HDNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuyenAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.HDNhap[] HDNhaps {
            get {
                return this.HDNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapsField, value) != true)) {
                    this.HDNhapsField = value;
                    this.RaisePropertyChanged("HDNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuyenAdmin {
            get {
                return this.QuyenAdminField;
            }
            set {
                if ((this.QuyenAdminField.Equals(value) != true)) {
                    this.QuyenAdminField = value;
                    this.RaisePropertyChanged("QuyenAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhuyenMai", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class KhuyenMai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaKM {
            get {
                return this.MaKMField;
            }
            set {
                if ((this.MaKMField.Equals(value) != true)) {
                    this.MaKMField = value;
                    this.RaisePropertyChanged("MaKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayBD {
            get {
                return this.NgayBDField;
            }
            set {
                if ((this.NgayBDField.Equals(value) != true)) {
                    this.NgayBDField = value;
                    this.RaisePropertyChanged("NgayBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayKT {
            get {
                return this.NgayKTField;
            }
            set {
                if ((this.NgayKTField.Equals(value) != true)) {
                    this.NgayKTField = value;
                    this.RaisePropertyChanged("NgayKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKM {
            get {
                return this.TenKMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKMField, value) != true)) {
                    this.TenKMField = value;
                    this.RaisePropertyChanged("TenKM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loai", Namespace="http://schemas.datacontract.org/2004/07/Service_GiayDep.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Loai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GiayDep.Service_CTDH.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GiayDep.Service_CTDH.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_CTDH.IService_CTDH")]
    public interface IService_CTDH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/ThemCTDH", ReplyAction="http://tempuri.org/IService_CTDH/ThemCTDHResponse")]
        bool ThemCTDH(int MaDH, int MaSP, int MaMau, int MaSize, int SoLuong, decimal DonGia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/ThemCTDH", ReplyAction="http://tempuri.org/IService_CTDH/ThemCTDHResponse")]
        System.Threading.Tasks.Task<bool> ThemCTDHAsync(int MaDH, int MaSP, int MaMau, int MaSize, int SoLuong, decimal DonGia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/LsCTDH", ReplyAction="http://tempuri.org/IService_CTDH/LsCTDHResponse")]
        GiayDep.Service_CTDH.SanPham_Price[] LsCTDH(int MaDH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/LsCTDH", ReplyAction="http://tempuri.org/IService_CTDH/LsCTDHResponse")]
        System.Threading.Tasks.Task<GiayDep.Service_CTDH.SanPham_Price[]> LsCTDHAsync(int MaDH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/LayCTHDN", ReplyAction="http://tempuri.org/IService_CTDH/LayCTHDNResponse")]
        GiayDep.Service_CTDH.CTDH[] LayCTHDN(int MaHDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/LayCTHDN", ReplyAction="http://tempuri.org/IService_CTDH/LayCTHDNResponse")]
        System.Threading.Tasks.Task<GiayDep.Service_CTDH.CTDH[]> LayCTHDNAsync(int MaHDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/XoaCTDH", ReplyAction="http://tempuri.org/IService_CTDH/XoaCTDHResponse")]
        bool XoaCTDH(int MaDH, int MaSP, int MaMau, int MaSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CTDH/XoaCTDH", ReplyAction="http://tempuri.org/IService_CTDH/XoaCTDHResponse")]
        System.Threading.Tasks.Task<bool> XoaCTDHAsync(int MaDH, int MaSP, int MaMau, int MaSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_CTDHChannel : GiayDep.Service_CTDH.IService_CTDH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_CTDHClient : System.ServiceModel.ClientBase<GiayDep.Service_CTDH.IService_CTDH>, GiayDep.Service_CTDH.IService_CTDH {
        
        public Service_CTDHClient() {
        }
        
        public Service_CTDHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_CTDHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CTDHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CTDHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ThemCTDH(int MaDH, int MaSP, int MaMau, int MaSize, int SoLuong, decimal DonGia) {
            return base.Channel.ThemCTDH(MaDH, MaSP, MaMau, MaSize, SoLuong, DonGia);
        }
        
        public System.Threading.Tasks.Task<bool> ThemCTDHAsync(int MaDH, int MaSP, int MaMau, int MaSize, int SoLuong, decimal DonGia) {
            return base.Channel.ThemCTDHAsync(MaDH, MaSP, MaMau, MaSize, SoLuong, DonGia);
        }
        
        public GiayDep.Service_CTDH.SanPham_Price[] LsCTDH(int MaDH) {
            return base.Channel.LsCTDH(MaDH);
        }
        
        public System.Threading.Tasks.Task<GiayDep.Service_CTDH.SanPham_Price[]> LsCTDHAsync(int MaDH) {
            return base.Channel.LsCTDHAsync(MaDH);
        }
        
        public GiayDep.Service_CTDH.CTDH[] LayCTHDN(int MaHDN) {
            return base.Channel.LayCTHDN(MaHDN);
        }
        
        public System.Threading.Tasks.Task<GiayDep.Service_CTDH.CTDH[]> LayCTHDNAsync(int MaHDN) {
            return base.Channel.LayCTHDNAsync(MaHDN);
        }
        
        public bool XoaCTDH(int MaDH, int MaSP, int MaMau, int MaSize) {
            return base.Channel.XoaCTDH(MaDH, MaSP, MaMau, MaSize);
        }
        
        public System.Threading.Tasks.Task<bool> XoaCTDHAsync(int MaDH, int MaSP, int MaMau, int MaSize) {
            return base.Channel.XoaCTDHAsync(MaDH, MaSP, MaMau, MaSize);
        }
    }
}
