//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_GiayDep.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    [KnownType(typeof(CTDH))]

    public partial class DonHang
    {
        public DonHang()
        {
            this.CTDHs = new List<CTDH>();
        }

        [DataMember]
        public int MaDH { get; set; }
        [DataMember]
        public int MaKH { get; set; }
        [DataMember]
        public Nullable<int> MaNV { get; set; }
        [DataMember]
        public Nullable<System.DateTime> NgayLap { get; set; }
        [DataMember]
        public Nullable<decimal> TongTien { get; set; }
        [DataMember]
        public string TinhTrang { get; set; }

        [DataMember]
        public virtual List<CTDH> CTDHs { get; set; }
        [DataMember]
        public virtual KhachHang KhachHang { get; set; }
        [DataMember]
        public virtual NhanVien NhanVien { get; set; }
    }
}
