//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_GiayDep.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    [KnownType(typeof(CTDH))]
    [KnownType(typeof(CTHoaDonNhap))]
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CTDHs = new List<CTDH>();
            this.CTHoaDonNhaps = new List<CTHoaDonNhap>();
        }

        [DataMember]
        public int MaSP { get; set; }
        [DataMember]
        public string TenSP { get; set; }
        [DataMember]
        public Nullable<int> MaLoai { get; set; }
        [DataMember]
        public string ThuongHieu { get; set; }
        [DataMember]
        public Nullable<decimal> GiaSP { get; set; }
        [DataMember]
        public string HinhAnh { get; set; }
        [DataMember]
        public string HinhAnh1 { get; set; }
        [DataMember]
        public string HinhAnh2 { get; set; }
        [DataMember]
        public string HinhAnh3 { get; set; }
        [DataMember]
        public Nullable<int> SoLuong { get; set; }
        [DataMember]
        public string MoTa { get; set; }
        [DataMember]
        public Nullable<int> KM { get; set; }
        [DataMember]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [DataMember]
        public Nullable<int> GiaKM { get; set; }

        [DataMember]
        public virtual List<CTDH> CTDHs { get; set; }
        [DataMember]
        public virtual List<CTHoaDonNhap> CTHoaDonNhaps { get; set; }
        [DataMember]
        public virtual Loai Loai { get; set; }
        [DataMember]
        public virtual Mau Mau { get; set; }
    }
}
