//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminQuanLyShop.Service_HoaDonNhap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HDNhap", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HDNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaHDNField;
        
        private System.Nullable<int> MaNCCField;
        
        private System.Nullable<int> MaNVField;
        
        private System.Nullable<System.DateTime> NgayNhapField;
        
        private System.Nullable<decimal> TongTienField;
        
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.NhaCungCap NhaCungCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.NhanVien NhanVienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaHDN {
            get {
                return this.MaHDNField;
            }
            set {
                if ((this.MaHDNField.Equals(value) != true)) {
                    this.MaHDNField = value;
                    this.RaisePropertyChanged("MaHDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AdminQuanLyShop.Service_HoaDonNhap.NhaCungCap NhaCungCap {
            get {
                return this.NhaCungCapField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaCungCapField, value) != true)) {
                    this.NhaCungCapField = value;
                    this.RaisePropertyChanged("NhaCungCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AdminQuanLyShop.Service_HoaDonNhap.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaCungCap", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NhaCungCap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] HDNhapsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenNCC {
            get {
                return this.TenNCCField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNCCField, value) != true)) {
                    this.TenNCCField = value;
                    this.RaisePropertyChanged("TenNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SoTK {
            get {
                return this.SoTKField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTKField, value) != true)) {
                    this.SoTKField = value;
                    this.RaisePropertyChanged("SoTK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] HDNhaps {
            get {
                return this.HDNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapsField, value) != true)) {
                    this.HDNhapsField = value;
                    this.RaisePropertyChanged("HDNhaps");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        private System.Nullable<int> QuyenAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] HDNhapsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> QuyenAdmin {
            get {
                return this.QuyenAdminField;
            }
            set {
                if ((this.QuyenAdminField.Equals(value) != true)) {
                    this.QuyenAdminField = value;
                    this.RaisePropertyChanged("QuyenAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] HDNhaps {
            get {
                return this.HDNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapsField, value) != true)) {
                    this.HDNhapsField = value;
                    this.RaisePropertyChanged("HDNhaps");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTHDN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CTHDN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaHDNField;
        
        private int MaSPField;
        
        private int MaMauField;
        
        private int MaSizeField;
        
        private System.Nullable<int> SLField;
        
        private System.Nullable<decimal> GiaNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.HDNhap HDNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaHDN {
            get {
                return this.MaHDNField;
            }
            set {
                if ((this.MaHDNField.Equals(value) != true)) {
                    this.MaHDNField = value;
                    this.RaisePropertyChanged("MaHDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.GiaNhapField;
            }
            set {
                if ((this.GiaNhapField.Equals(value) != true)) {
                    this.GiaNhapField = value;
                    this.RaisePropertyChanged("GiaNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AdminQuanLyShop.Service_HoaDonNhap.HDNhap HDNhap {
            get {
                return this.HDNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.HDNhapField, value) != true)) {
                    this.HDNhapField = value;
                    this.RaisePropertyChanged("HDNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AdminQuanLyShop.Service_HoaDonNhap.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AdminQuanLyShop.Service_HoaDonNhap.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mau", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mau : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Kho[] KhoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenMau {
            get {
                return this.TenMauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMauField, value) != true)) {
                    this.TenMauField = value;
                    this.RaisePropertyChanged("TenMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AdminQuanLyShop.Service_HoaDonNhap.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        private System.Nullable<int> MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThuongHieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        private System.Nullable<int> MaKMField;
        
        private System.Nullable<System.DateTime> NgayDangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Kho[] KhoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.KhuyenMai KhuyenMaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Loai LoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ThuongHieu {
            get {
                return this.ThuongHieuField;
            }
            set {
                if ((object.ReferenceEquals(this.ThuongHieuField, value) != true)) {
                    this.ThuongHieuField = value;
                    this.RaisePropertyChanged("ThuongHieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> MaKM {
            get {
                return this.MaKMField;
            }
            set {
                if ((this.MaKMField.Equals(value) != true)) {
                    this.MaKMField = value;
                    this.RaisePropertyChanged("MaKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> NgayDang {
            get {
                return this.NgayDangField;
            }
            set {
                if ((this.NgayDangField.Equals(value) != true)) {
                    this.NgayDangField = value;
                    this.RaisePropertyChanged("NgayDang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MoTaCT {
            get {
                return this.MoTaCTField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaCTField, value) != true)) {
                    this.MoTaCTField = value;
                    this.RaisePropertyChanged("MoTaCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public AdminQuanLyShop.Service_HoaDonNhap.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public AdminQuanLyShop.Service_HoaDonNhap.KhuyenMai KhuyenMai {
            get {
                return this.KhuyenMaiField;
            }
            set {
                if ((object.ReferenceEquals(this.KhuyenMaiField, value) != true)) {
                    this.KhuyenMaiField = value;
                    this.RaisePropertyChanged("KhuyenMai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public AdminQuanLyShop.Service_HoaDonNhap.Loai Loai {
            get {
                return this.LoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiField, value) != true)) {
                    this.LoaiField = value;
                    this.RaisePropertyChanged("Loai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Size", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Size : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaSizeField;
        
        private System.Nullable<int> Size1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Kho[] KhoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Size1 {
            get {
                return this.Size1Field;
            }
            set {
                if ((this.Size1Field.Equals(value) != true)) {
                    this.Size1Field = value;
                    this.RaisePropertyChanged("Size1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTHDN[] CTHDNs {
            get {
                return this.CTHDNsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTHDNsField, value) != true)) {
                    this.CTHDNsField = value;
                    this.RaisePropertyChanged("CTHDNs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AdminQuanLyShop.Service_HoaDonNhap.Kho[] Khoes {
            get {
                return this.KhoesField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoesField, value) != true)) {
                    this.KhoesField = value;
                    this.RaisePropertyChanged("Khoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTDH", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CTDH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaDHField;
        
        private int MaSPField;
        
        private int MaSizeField;
        
        private int MaMauField;
        
        private System.Nullable<int> SLField;
        
        private System.Nullable<decimal> DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.DonHang DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AdminQuanLyShop.Service_HoaDonNhap.DonHang DonHang {
            get {
                return this.DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangField, value) != true)) {
                    this.DonHangField = value;
                    this.RaisePropertyChanged("DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AdminQuanLyShop.Service_HoaDonNhap.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AdminQuanLyShop.Service_HoaDonNhap.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kho", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaSPField;
        
        private int MaMauField;
        
        private int MaSizeField;
        
        private System.Nullable<int> SLField;
        
        private System.Nullable<decimal> GiaBanField;
        
        private System.Nullable<decimal> GiaNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Mau MauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.Size SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int MaMau {
            get {
                return this.MaMauField;
            }
            set {
                if ((this.MaMauField.Equals(value) != true)) {
                    this.MaMauField = value;
                    this.RaisePropertyChanged("MaMau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MaSize {
            get {
                return this.MaSizeField;
            }
            set {
                if ((this.MaSizeField.Equals(value) != true)) {
                    this.MaSizeField = value;
                    this.RaisePropertyChanged("MaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> SL {
            get {
                return this.SLField;
            }
            set {
                if ((this.SLField.Equals(value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> GiaNhap {
            get {
                return this.GiaNhapField;
            }
            set {
                if ((this.GiaNhapField.Equals(value) != true)) {
                    this.GiaNhapField = value;
                    this.RaisePropertyChanged("GiaNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AdminQuanLyShop.Service_HoaDonNhap.Mau Mau {
            get {
                return this.MauField;
            }
            set {
                if ((object.ReferenceEquals(this.MauField, value) != true)) {
                    this.MauField = value;
                    this.RaisePropertyChanged("Mau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AdminQuanLyShop.Service_HoaDonNhap.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AdminQuanLyShop.Service_HoaDonNhap.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaDHField;
        
        private System.Nullable<int> MaKHField;
        
        private System.Nullable<System.DateTime> NgayMuaField;
        
        private System.Nullable<decimal> TongTienField;
        
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NVDuyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.KhachHang KhachHangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> NgayMua {
            get {
                return this.NgayMuaField;
            }
            set {
                if ((this.NgayMuaField.Equals(value) != true)) {
                    this.NgayMuaField = value;
                    this.RaisePropertyChanged("NgayMua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NVDuyet {
            get {
                return this.NVDuyetField;
            }
            set {
                if ((object.ReferenceEquals(this.NVDuyetField, value) != true)) {
                    this.NVDuyetField = value;
                    this.RaisePropertyChanged("NVDuyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AdminQuanLyShop.Service_HoaDonNhap.CTDH[] CTDHs {
            get {
                return this.CTDHsField;
            }
            set {
                if ((object.ReferenceEquals(this.CTDHsField, value) != true)) {
                    this.CTDHsField = value;
                    this.RaisePropertyChanged("CTDHs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AdminQuanLyShop.Service_HoaDonNhap.KhachHang KhachHang {
            get {
                return this.KhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachHangField, value) != true)) {
                    this.KhachHangField = value;
                    this.RaisePropertyChanged("KhachHang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        private System.Nullable<System.DateTime> NgayDangKiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.DonHang[] DonHangsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> NgayDangKi {
            get {
                return this.NgayDangKiField;
            }
            set {
                if ((this.NgayDangKiField.Equals(value) != true)) {
                    this.NgayDangKiField = value;
                    this.RaisePropertyChanged("NgayDangKi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AdminQuanLyShop.Service_HoaDonNhap.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhuyenMai", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KhuyenMai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKMField;
        
        private System.Nullable<System.DateTime> NgayBDField;
        
        private System.Nullable<System.DateTime> NgayKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.SanPham[] SanPhamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaKM {
            get {
                return this.MaKMField;
            }
            set {
                if ((this.MaKMField.Equals(value) != true)) {
                    this.MaKMField = value;
                    this.RaisePropertyChanged("MaKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKM {
            get {
                return this.TenKMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKMField, value) != true)) {
                    this.TenKMField = value;
                    this.RaisePropertyChanged("TenKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> NgayBD {
            get {
                return this.NgayBDField;
            }
            set {
                if ((this.NgayBDField.Equals(value) != true)) {
                    this.NgayBDField = value;
                    this.RaisePropertyChanged("NgayBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> NgayKT {
            get {
                return this.NgayKTField;
            }
            set {
                if ((this.NgayKTField.Equals(value) != true)) {
                    this.NgayKTField = value;
                    this.RaisePropertyChanged("NgayKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AdminQuanLyShop.Service_HoaDonNhap.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loai", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Loai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminQuanLyShop.Service_HoaDonNhap.SanPham[] SanPhamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AdminQuanLyShop.Service_HoaDonNhap.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_HoaDonNhap.Service_HoaDonNhapSoap")]
    public interface Service_HoaDonNhapSoap {
        
        // CODEGEN: Generating message contract since element name LayTatCaHoaDonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayTatCaHoaDon", ReplyAction="*")]
        AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse LayTatCaHoaDon(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayTatCaHoaDon", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse> LayTatCaHoaDonAsync(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMotHoaDon", ReplyAction="*")]
        int LayMotHoaDon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMotHoaDon", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LayMotHoaDonAsync();
        
        // CODEGEN: Generating message contract since element name NgayLap from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHDNVaTraVeMaDHN", ReplyAction="*")]
        AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse ThemHDNVaTraVeMaDHN(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHDNVaTraVeMaDHN", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse> ThemHDNVaTraVeMaDHNAsync(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest request);
        
        // CODEGEN: Generating message contract since element name NgayLap from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaHDN", ReplyAction="*")]
        AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse SuaHDN(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaHDN", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse> SuaHDNAsync(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaHDN", ReplyAction="*")]
        bool XoaHDN(int MaHDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaHDN", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> XoaHDNAsync(int MaHDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DuyetHD", ReplyAction="*")]
        bool DuyetHD(int MaHDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DuyetHD", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DuyetHDAsync(int MaHDN);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayTatCaHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayTatCaHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequestBody Body;
        
        public LayTatCaHoaDonRequest() {
        }
        
        public LayTatCaHoaDonRequest(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LayTatCaHoaDonRequestBody {
        
        public LayTatCaHoaDonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayTatCaHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayTatCaHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponseBody Body;
        
        public LayTatCaHoaDonResponse() {
        }
        
        public LayTatCaHoaDonResponse(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LayTatCaHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] LayTatCaHoaDonResult;
        
        public LayTatCaHoaDonResponseBody() {
        }
        
        public LayTatCaHoaDonResponseBody(AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] LayTatCaHoaDonResult) {
            this.LayTatCaHoaDonResult = LayTatCaHoaDonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemHDNVaTraVeMaDHNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemHDNVaTraVeMaDHN", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequestBody Body;
        
        public ThemHDNVaTraVeMaDHNRequest() {
        }
        
        public ThemHDNVaTraVeMaDHNRequest(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemHDNVaTraVeMaDHNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MaNCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MaNV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NgayLap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal TongTien;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TinhTrang;
        
        public ThemHDNVaTraVeMaDHNRequestBody() {
        }
        
        public ThemHDNVaTraVeMaDHNRequestBody(int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            this.MaNCC = MaNCC;
            this.MaNV = MaNV;
            this.NgayLap = NgayLap;
            this.TongTien = TongTien;
            this.TinhTrang = TinhTrang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemHDNVaTraVeMaDHNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemHDNVaTraVeMaDHNResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponseBody Body;
        
        public ThemHDNVaTraVeMaDHNResponse() {
        }
        
        public ThemHDNVaTraVeMaDHNResponse(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemHDNVaTraVeMaDHNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ThemHDNVaTraVeMaDHNResult;
        
        public ThemHDNVaTraVeMaDHNResponseBody() {
        }
        
        public ThemHDNVaTraVeMaDHNResponseBody(int ThemHDNVaTraVeMaDHNResult) {
            this.ThemHDNVaTraVeMaDHNResult = ThemHDNVaTraVeMaDHNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuaHDNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuaHDN", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequestBody Body;
        
        public SuaHDNRequest() {
        }
        
        public SuaHDNRequest(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SuaHDNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MaHDN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MaNCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MaNV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NgayLap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal TongTien;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int TinhTrang;
        
        public SuaHDNRequestBody() {
        }
        
        public SuaHDNRequestBody(int MaHDN, int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            this.MaHDN = MaHDN;
            this.MaNCC = MaNCC;
            this.MaNV = MaNV;
            this.NgayLap = NgayLap;
            this.TongTien = TongTien;
            this.TinhTrang = TinhTrang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuaHDNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuaHDNResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponseBody Body;
        
        public SuaHDNResponse() {
        }
        
        public SuaHDNResponse(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SuaHDNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SuaHDNResult;
        
        public SuaHDNResponseBody() {
        }
        
        public SuaHDNResponseBody(bool SuaHDNResult) {
            this.SuaHDNResult = SuaHDNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_HoaDonNhapSoapChannel : AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_HoaDonNhapSoapClient : System.ServiceModel.ClientBase<AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap>, AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap {
        
        public Service_HoaDonNhapSoapClient() {
        }
        
        public Service_HoaDonNhapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_HoaDonNhapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_HoaDonNhapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_HoaDonNhapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.LayTatCaHoaDon(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest request) {
            return base.Channel.LayTatCaHoaDon(request);
        }
        
        public AdminQuanLyShop.Service_HoaDonNhap.HDNhap[] LayTatCaHoaDon() {
            AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequestBody();
            AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse retVal = ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).LayTatCaHoaDon(inValue);
            return retVal.Body.LayTatCaHoaDonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse> AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.LayTatCaHoaDonAsync(AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest request) {
            return base.Channel.LayTatCaHoaDonAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonResponse> LayTatCaHoaDonAsync() {
            AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.LayTatCaHoaDonRequestBody();
            return ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).LayTatCaHoaDonAsync(inValue);
        }
        
        public int LayMotHoaDon() {
            return base.Channel.LayMotHoaDon();
        }
        
        public System.Threading.Tasks.Task<int> LayMotHoaDonAsync() {
            return base.Channel.LayMotHoaDonAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.ThemHDNVaTraVeMaDHN(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest request) {
            return base.Channel.ThemHDNVaTraVeMaDHN(request);
        }
        
        public int ThemHDNVaTraVeMaDHN(int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequestBody();
            inValue.Body.MaNCC = MaNCC;
            inValue.Body.MaNV = MaNV;
            inValue.Body.NgayLap = NgayLap;
            inValue.Body.TongTien = TongTien;
            inValue.Body.TinhTrang = TinhTrang;
            AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse retVal = ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).ThemHDNVaTraVeMaDHN(inValue);
            return retVal.Body.ThemHDNVaTraVeMaDHNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse> AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.ThemHDNVaTraVeMaDHNAsync(AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest request) {
            return base.Channel.ThemHDNVaTraVeMaDHNAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNResponse> ThemHDNVaTraVeMaDHNAsync(int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.ThemHDNVaTraVeMaDHNRequestBody();
            inValue.Body.MaNCC = MaNCC;
            inValue.Body.MaNV = MaNV;
            inValue.Body.NgayLap = NgayLap;
            inValue.Body.TongTien = TongTien;
            inValue.Body.TinhTrang = TinhTrang;
            return ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).ThemHDNVaTraVeMaDHNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.SuaHDN(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest request) {
            return base.Channel.SuaHDN(request);
        }
        
        public bool SuaHDN(int MaHDN, int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequestBody();
            inValue.Body.MaHDN = MaHDN;
            inValue.Body.MaNCC = MaNCC;
            inValue.Body.MaNV = MaNV;
            inValue.Body.NgayLap = NgayLap;
            inValue.Body.TongTien = TongTien;
            inValue.Body.TinhTrang = TinhTrang;
            AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse retVal = ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).SuaHDN(inValue);
            return retVal.Body.SuaHDNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse> AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap.SuaHDNAsync(AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest request) {
            return base.Channel.SuaHDNAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminQuanLyShop.Service_HoaDonNhap.SuaHDNResponse> SuaHDNAsync(int MaHDN, int MaNCC, int MaNV, string NgayLap, decimal TongTien, int TinhTrang) {
            AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest inValue = new AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequest();
            inValue.Body = new AdminQuanLyShop.Service_HoaDonNhap.SuaHDNRequestBody();
            inValue.Body.MaHDN = MaHDN;
            inValue.Body.MaNCC = MaNCC;
            inValue.Body.MaNV = MaNV;
            inValue.Body.NgayLap = NgayLap;
            inValue.Body.TongTien = TongTien;
            inValue.Body.TinhTrang = TinhTrang;
            return ((AdminQuanLyShop.Service_HoaDonNhap.Service_HoaDonNhapSoap)(this)).SuaHDNAsync(inValue);
        }
        
        public bool XoaHDN(int MaHDN) {
            return base.Channel.XoaHDN(MaHDN);
        }
        
        public System.Threading.Tasks.Task<bool> XoaHDNAsync(int MaHDN) {
            return base.Channel.XoaHDNAsync(MaHDN);
        }
        
        public bool DuyetHD(int MaHDN) {
            return base.Channel.DuyetHD(MaHDN);
        }
        
        public System.Threading.Tasks.Task<bool> DuyetHDAsync(int MaHDN) {
            return base.Channel.DuyetHDAsync(MaHDN);
        }
    }
}
